In [ ]:
import pandas as pd

path = "../data/"

In [ ]:
df = pd.read_csv(
    path + "sentiment140.csv",
    encoding="latin-1",
    header=None
)

In [ ]:
df.columns = ["target", "id", "date", "flag", "user", "text"]
df.head()

,target,id,date,flag,user,text
0,4,2046362316,Fri Jun 05 12:04:14 PDT 2009,NO_QUERY,winecliQ,@VERGEwine Thx for the #ff lovin - now if that...
1,0,1984664187,Sun May 31 15:33:25 PDT 2009,NO_QUERY,XeBeans,another WONDERFUL weekend! i almost hate to go...
2,0,2187830458,Mon Jun 15 20:52:20 PDT 2009,NO_QUERY,ACTinglikeamama,belly pushing against jeans - only three month...
3,0,1992717155,Mon Jun 01 09:12:29 PDT 2009,NO_QUERY,scarletsighting,missing London. with all honesty.
4,4,1792666808,Wed May 13 23:50:50 PDT 2009,NO_QUERY,sambirchall,Wow!!! I can go on twitwer on my iPod that's ...

In [ ]:
df = df[['target', 'text']]

In [ ]:
df['label'] = df['target'].replace({
    0: 'negative',
    4: 'positive'
})

In [ ]:
df.head()
df['label'].value_counts()

label
negative    10000
positive    10000
Name: count, dtype: int64

In [ ]:
df = df.groupby('label', group_keys=False).sample(
    n=10000,
    random_state=42
)

In [ ]:
df['label'].value_counts()

label
negative    10000
positive    10000
Name: count, dtype: int64

In [ ]:
df_air = pd.read_csv("../data/tweets2.csv")
df_air.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
df_air = df_air[['text', 'airline_sentiment']]

In [ ]:
df_air.head()

                                                text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative

In [ ]:
df_air = df_air.rename(columns={
    'airline_sentiment': 'label'
})

In [ ]:
df_air.head()

                                                text     label
0                @VirginAmerica What @dhepburn said.   neutral
1  @VirginAmerica plus you've added commercials t...  positive
2  @VirginAmerica I didn't today... Must mean I n...   neutral
3  @VirginAmerica it's really aggressive to blast...  negative
4  @VirginAmerica and it's a really big bad thing...  negative

In [ ]:
df_air['label'].value_counts()

label
negative    9178
neutral     3099
positive    2363
Name: count, dtype: int64

In [ ]:
df_neu = df_air[df_air['label'] == 'neutral']

df_neu_upsampled = df_neu.sample(
    n=8000, 
    replace=True,   
    random_state=42
)

In [ ]:
df_pos = df[df['label'] == 'positive'].sample(n=8000, random_state=42)
df_neg = df[df['label'] == 'negative'].sample(n=8000, random_state=42)

df_final = pd.concat([df_pos, df_neg, df_neu_upsampled])

In [ ]:
df_final['label'].value_counts()

label
positive    8000
negative    8000
neutral     8000
Name: count, dtype: int64

In [ ]:
import re

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)   
    text = re.sub(r"@\w+", "", text)      
    text = re.sub(r"#", "", text)      
    text = re.sub(r"[^a-z\s]", " ", text) 
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [ ]:
df_final['clean_text'] = df_final['text'].astype(str).apply(preprocess)

In [ ]:
df_final[['text','clean_text']].head()

,text,clean_text
393952,Just cleaned out my baby's beta fish tank. Now...,just cleaned out my baby s beta fish tank now ...
1545423,"morning everyone - v.tired, need to get the mo...",morning everyone v tired need to get the morni...
446201,going back to santos in a couple of hours,going back to santos in a couple of hours
458206,@NickWayne87 lmaoo exactly !! and thank you th...,lmaoo exactly and thank you thats much appreci...
828350,Vvv that was rachel not me rachel's vagina sme...,vvv that was rachel not me rachel s vagina sme...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1,2),
    stop_words='english'
)

X = vectorizer.fit_transform(df_final['clean_text'])
y = df_final['label']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    negative       0.72      0.68      0.70      1600
     neutral       0.89      0.92      0.91      1600
    positive       0.68      0.70      0.69      1600

    accuracy                           0.77      4800
   macro avg       0.76      0.77      0.77      4800
weighted avg       0.76      0.77      0.77      4800

In [51]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [52]:
from sklearn.svm import LinearSVC
svm = LinearSVC()
svm.fit(X_train, y_train)

LinearSVC()

In [53]:
from sklearn.metrics import classification_report

for name, m in {
    "LogReg": model,
    "NB": nb,
    "SVM": svm
}.items():
    preds = m.predict(X_test)
    print(f"\n{name}\n", classification_report(y_test, preds))

LogReg
               precision    recall  f1-score   support

    negative       0.72      0.68      0.70      1600
     neutral       0.89      0.92      0.91      1600
    positive       0.68      0.70      0.69      1600

    accuracy                           0.77      4800
   macro avg       0.76      0.77      0.77      4800
weighted avg       0.76      0.77      0.77      4800


NB
               precision    recall  f1-score   support

    negative       0.67      0.71      0.69      1600
     neutral       0.92      0.87      0.90      1600
    positive       0.67      0.66      0.66      1600

    accuracy                           0.75      4800
   macro avg       0.75      0.75      0.75      4800
weighted avg       0.75      0.75      0.75      4800


SVM
               precision    recall  f1-score   support

    negative       0.71      0.68      0.69      1600
     neutral       0.91      0.93      0.92      1600
    positive       0.67      0.69      0.68      1600

    accuracy                           0.76      4800
   macro avg       0.76      0.76      0.76      4800
weighted avg       0.76      0.76      0.76      4800

In [54]:
import pickle

pickle.dump(model, open("../model.pkl", "wb"))
pickle.dump(vectorizer, open("../vectorizer.pkl", "wb"))

In [63]:
import numpy as np

labels = model.classes_   

def predict_with_threshold(texts, threshold=0.5):
    texts_clean = [preprocess(t) for t in texts]
    X = vectorizer.transform(texts_clean)
    
    probs = model.predict_proba(X)
    
    final_preds = []
    
    for p in probs:
        max_prob = np.max(p)
        label = labels[np.argmax(p)]
        
        if max_prob < threshold:
            final_preds.append("neutral")
        else:
            final_preds.append(label)
    
    return final_preds

In [64]:
sample = [
    "I love this product",
    "This is terrible",
    "It is okay, nothing special"
]

print(predict_with_threshold(sample))

['positive', 'negative', 'positive']

In [66]:
def credibility(followers, likes):
    if followers > 500 and likes > 10:
        return "Authentic"
    return "Suspicious"

In [67]:
from collections import Counter

counts = Counter(preds)

total = len(preds)

for k in counts:
    print(k, round(counts[k] / total * 100, 2), "%")

neutral 33.98 %
positive 34.29 %
negative 31.73 %

In [93]:
def get_rss_data():
    feed = feedparser.parse(
        "https://www.reddit.com/r/technology/.rss",
        request_headers={'User-Agent': 'sentiment-app'}
    )
    return [entry.title for entry in feed.entries]

In [69]:
pip install feedparser

Collecting feedparser
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting sgmllib3k (from feedparser)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (pyproject.toml) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6090 sha256=be1502579b6335ad4b49442197da47e0518951b835d7f27a42b1a6208f0eee59
  Stored in directory: /Users/harshitasaxena/Library/Caches/pip/wheels/e3/43/83/0f6e317d0698ac38ee6a5b6e214019c167057916a11bad91ab
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [feedparser]
Successfully installed feedparser-6.0.12 sgmllib3k-1.0.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [71]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

In [79]:
import os
from dotenv import load_dotenv

load_dotenv()

NEWS_API_KEY = os.getenv("NEWS_API_KEY")